#!/bin/bash

echo "=========================================="
echo "  阿里云安全组配置向导"
echo "=========================================="
echo ""
echo "步骤1: 编辑脚本，填入 AccessKey Secret"
echo ""
echo "  nano /root/run_setup.sh"
echo ""
echo "  找到这一行："
echo "  ACCESS_KEY_SECRET=\"<请在这里填入你的AccessKey Secret>\""
echo ""
echo "  替换为："
echo "  ACCESS_KEY_SECRET=\"<你的真实Secret>\""
echo ""
echo "  保存: Ctrl+O, 回车, Ctrl+X"
echo ""
echo "步骤2: 执行脚本"
echo ""
echo "  bash /root/run_setup.sh"
echo ""
echo "步骤3: 测试服务（等待1-2分钟后）"
echo ""
echo "  curl http://59.110.40.73:8081/health"
echo ""
echo "=========================================="
